POST http://localhost:1818/api/newsletter
Content-Type: application/json

{
    "email": "thomas.test@example.com"
}

###
DELETE http://localhost:1818/api/newsletter
Content-Type: application/json

{
    id: 2
}