### Ajout d'une promotion avec un prix fixe
POST http://localhost:1818/api/promotion
Content-Type: application/json

{
  "title": "Promo huile de lavande",
  "description": "Prix spécial printemps",
  "type": "fixed",                        
  "value": 8.99,                          
  "start_date": "2025-05-10T00:00:00.000Z",
  "end_date": "2025-05-20T00:00:00.000Z",
  "product_id": 1                         
}

### Ajout d'une promotion avec un pourcentage
POST http://localhost:1818/api/promotion
Content-Type: application/json

{
  "title": "Promo huile de lavande",
  "description": "Prix spécial printemps",
  "type": "percentage",                        
  "value": 20,                          
  "start_date": "2025-05-10T00:00:00.000Z",
  "end_date": "2025-05-20T00:00:00.000Z",
  "product_id": 2                         
}

### Requête invalide 
POST http://localhost:1818/api/promotion
Content-Type: application/json

{
  "product_id": 4
}

### Modifier une promotion 
PUT http://localhost:1818/api/promotion/1
Content-Type: application/json

{
  "title": "Promo huile de lavande",
  "description": "Prix spécial printemps",
  "type": "fixed",                        
  "value": 2,                          
  "start_date": "2025-05-10T00:00:00.000Z",
  "end_date": "2025-05-20T00:00:00.000Z",
  "product_id": 2                         
}

### Supprimer une promotion
DELETE http://localhost:1818/api/promotion/1
